# src/Acme/AccountBundle/Resources/config/routing.yml
account_register:
    path:     /register
    defaults: { _controller: BloggerAccountBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: BloggerAccountBundle:Account:create }