parameters:
#    blogger_account.example.class: Blogger\AccountBundle\Example

services:
#    blogger_account.example:
#        class: %blogger_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
